# permissions for end users to view smartcontracts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-go
    app.kubernetes.io/managed-by: kustomize
  name: smartcontract-viewer-role
rules:
- apiGroups:
  - core.paladin.io
  resources:
  - smartcontracts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.paladin.io
  resources:
  - smartcontracts/status
  verbs:
  - get
