apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.operator.name }}
rules:
- apiGroups:
  - core.paladin.io
  resources:
  - nodes
  - smartcontracts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.paladin.io
  resources:
  - nodes/status
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - get
  - list
  - create
  - delete
- apiGroups:
  - ""  # core
  resources:
  - services
  - configmaps
  verbs:
  - get
  - list
  - create
  - delete
  - update
  - patch
