apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.operator.namespace }}
  {{- with .Values.operator.configMap.annotations }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.operator.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.operator.configMap.data }}
  {{ $key }}: |
    {{ $value | nindent 4 }}
  {{- end }}
