apiVersion: core.paladin.io/v1alpha1
kind: PaladinRegistry
metadata:
  labels:
    app.kubernetes.io/name: operator-go
    app.kubernetes.io/managed-by: kustomize
  name: evm-registry
spec:
  type: evm
  evm:
    smartContractDeployment: registry
