# To convert your JSON content to base64, use the following command:
# echo -n '<your-json>' | base64
#
# Example:
# echo -n '{"nodeName":"node1","db":{"type":"sqlite","sqlite":{"uri":":memory:","autoMigrate":true,"migrationsDir":"./db/migrations/sqlite","debugQueries":true}},"grpc":{"shutdownTimeout":0},"rpcServer":{"http":{"port":0,"shutdownTimeout":0},"ws":{"disabled":true,"shutdownTimeout":0}},"blockchain":{"http":{"url":"http://localhost:8545"},"ws":{"url":"ws://localhost:8546","initialConnectAttempts":25}},"signer":{"keyDerivation":{"type":"bip32"},"keyStore":{"type":"static","static":{"keys":{"seed":{"encoding":"none","inline":"worth race crush harbor atom race scrub quit glimpse solution style adapt catalog cheese nothing"}}}}}}' | base64

apiVersion: core.paladin.io/v1alpha1
kind: Paladin
metadata:
  name: node1
spec:
  config: |
    log:
      level: debug
  database:
    mode: sidecarPostgres
    migrationMode: auto
  secretBackedSigners:
    - name: signer-1
      secret: node1.keys
      type: autoHDWallet