apiVersion: core.paladin.io/v1alpha1
kind: TransactionInvoke
metadata:
  labels:
    app.kubernetes.io/name: operator-go
    app.kubernetes.io/managed-by: kustomize
  name: zeto-anon
spec:
  node: node1
  from: zeto.deployer
  txType: public
  toTemplate: "{{ index .status.resolvedContractAddresses "noto-factory" }}"
  requiredContractDeployments:
  - "noto-factory"
  - "zeto-impl-anon"
  - "zeto-g16-check-hashes-value"
  - "zeto-g16-check-inputs-outputs"
  - "zeto-g16-check-inputs-outputs-batch"
  - "zeto-g16-verifier-anon"
  - "zeto-g16-verifier-anon-batch"
  paramsJSONTemplate: |
    {
      "implementation":        "{{ index .status.resolvedContractAddresses "zeto-impl-anon" }}",
      "depositVerifier":       "{{ index .status.resolvedContractAddresses "zeto-g16-check-hashes-value" }}",
      "withdrawVerifier":      "{{ index .status.resolvedContractAddresses "zeto-g16-check-inputs-outputs" }}",
      "batchWithdrawVerifier": "{{ index .status.resolvedContractAddresses "zeto-g16-check-inputs-outputs-batch" }}",
      "verifier":              "{{ index .status.resolvedContractAddresses "zeto-g16-verifier-anon" }}",
      "batchVerifier":         "{{ index .status.resolvedContractAddresses "zeto-g16-verifier-anon-batch" }}"
    }

