## Append samples of your project ##
resources:
- core_v1alpha1_paladin.yaml
- core_v1alpha1_besu.yaml
- core_v1alpha1_besugenesis.yaml
- core_v1alpha1_smartcontractdeployment_registry.yaml
- core_v1alpha1_smartcontractdeployment_noto.yaml
- core_v1alpha1_smartcontractdeployment_pente.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
