## Append samples of your project ##
resources:
- core_v1alpha1_paladin.yaml
- core_v1alpha1_besu.yaml
- core_v1alpha1_besugenesis.yaml
- core_v1alpha1_smartcontractdeployment_registry.yaml
- core_v1alpha1_smartcontractdeployment_noto.yaml
- core_v1alpha1_smartcontractdeployment_pente.yaml
- core_v1alpha1_paladinregistry.yaml
- core_v1alpha1_paladindomain_noto.yaml
- core_v1alpha1_paladindomain_pente.yaml
# - core_v1alpha1_paladindomain_zeto.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
