contracts:
  factory:
    abiAndBytecode:
      path: ./abis/ZetoFactory.json
  # the Zeto factory is a CloneFactory, which needs implementation
  # contracts to be set
  implementations:
    - name: Groth16Verifier_Anon
      abiAndBytecode:
        path: ./abis/Groth16Verifier_Anon.json
    - name: Groth16Verifier_AnonEnc
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonEnc.json
    - name: Groth16Verifier_AnonNullifier
      abiAndBytecode:
        path: ./abis/Groth16Verifier_AnonNullifier.json
    - name: Groth16Verifier_CheckHashesValue
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckHashesValue.json
    - name: Groth16Verifier_CheckInputsOutputsValue
      abiAndBytecode:
        path: ./abis/Groth16Verifier_CheckInputsOutputsValue.json
    - name: PoseidonUnit2L
      abiAndBytecode:
        path: ./abis/Poseidon2.json
    - name: PoseidonUnit3L
      abiAndBytecode:
        path: ./abis/Poseidon3.json
    - name: SmtLib
      abiAndBytecode:
        path: ./abis/SmtLib.json
    - name: Zeto_Anon
      verifier: Groth16Verifier_Anon
      circuitId: anon
      cloneable: true
      abiAndBytecode:
        path: ./abis/Zeto_Anon.json
    - name: Zeto_AnonEnc
      verifier: Groth16Verifier_AnonEnc
      circuitId: anon_enc
      cloneable: true
      abiAndBytecode:
        path: ./abis/Zeto_AnonEnc.json
    - name: Zeto_AnonNullifier
      verifier: Groth16Verifier_AnonNullifier
      circuitId: anon_nullifier
      cloneable: true
      abiAndBytecode:
        path: ./abis/Zeto_AnonNullifier.json
